rem @echo off
call conf.bat


SET INPUT=%1


SETLOCAL EnableDelayedExpansion
set INPUTNQ=!INPUT:~1,-1!
set INPUTREM=!INPUTNQ:###=rem!
SET O1=!INPUTREM:VMFOLDERHOLDER=%VMFOLDER%!
SET O2=!O1:COLLABN1VDIHOLDER=%COLLABN1VDI%!
SET O3=!O2:ORACLEISOPATHHOLDER=%ORACLEISOPATH%!
SET O4=!O3:DOWNLOADFOLDERHOLDER=%DOWNLOADFOLDER%!
SET O5=!O4:HOSTONLYNETNAMEHOLDER=%HOSTONLYNETNAME%!
SET OUT=!O5!
ECHO %OUT%>>vboxrun.bat
ENDLOCAL

